// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Welcome from "./Welcome.mjs";

function App(Props) {
  return React.createElement(Welcome.make, {
              title: "Hello, World"
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
