// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Welcome from "./welcome";
import * as ReactDom from "react-dom";

var welcome = Welcome.welcome;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, welcome), root);
}

export {
  welcome ,
  
}
/* welcome Not a pure module */
