// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var welcome = React.createElement("h1", undefined, "Hello, World");

export {
  welcome ,
  
}
/* welcome Not a pure module */
