// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Welcome(Props) {
  var title = Props.title;
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setText = match$1[1];
  var text = match$1[0];
  var onClick = function (evt) {
    evt.preventDefault();
    return setCount(function (prev) {
                return prev + 1 | 0;
              });
  };
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setText, (function (_prev) {
                  return value;
                }));
  };
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("div", undefined, React.createElement("h2", undefined, title), React.createElement("div", undefined, React.createElement("textarea", {
                      value: text,
                      onChange: onChange
                    })), React.createElement("div", {
                  style: {
                    fontWeight: "bold"
                  }
                }, "echo: " + text), React.createElement("div", {
                  style: {
                    marginTop: "8px"
                  }
                }, React.createElement("button", {
                      onClick: onClick
                    }, msg)));
}

var make = Welcome;

export {
  make ,
  
}
/* react Not a pure module */
